version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /usr/share/nginx/html:/usr/share/nginx/html
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
    ports:
      - 80:80
      - 443:443
    networks:
      - swecc_stack_swecc-network

  bot:
    image: swecc/swecc-bot:latest
    networks:
      - swecc_stack_swecc-network
    configs:
      - source: bot_env
        target: /app/.env
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  chronos:
    image: swecc/swecc-chronos:latest
    ports:
      - "8002:8002"
    networks:
      - swecc_stack_swecc-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - chronos_data:/app
    configs:
      - source: chronos_env
        target: /app/.env
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  redis:
    image: swecc/swecc-redis:latest
    networks:
      - swecc_stack_swecc-network
    volumes:
      - redis_data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  rabbit:
    image: swecc/swecc-rabbit:latest
    networks:
      - swecc_stack_swecc-network
    volumes:
      - swecc-rabbit-data:/var/lib/rabbitmq
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  scheduler:
    image: swecc/swecc-scheduler:latest
    networks:
      - swecc_stack_swecc-network
    configs:
      - source: scheduler_env
        target: /app/.env
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  server:
    image: swecc/swecc-server:latest
    networks:
      - swecc_stack_swecc-network
    configs:
      - source: server_env
        target: /app/.env
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  sockets:
    image: swecc/swecc-sockets:latest
    networks:
      - swecc_stack_swecc-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: sockets_env
        target: /app/.env
    deploy:
      replicas: 1
      restart_policy:
        condition: any

networks:
  swecc_stack_swecc-network:
    driver: overlay
    attachable: true

volumes:
  chronos_data:
  redis_data:
  swecc-rabbit-data:

configs:
  bot_env:
    external: true
  chronos_env:
    external: true
  scheduler_env:
    external: true
  server_env:
    external: true
  sockets_env:
    external: true